blank_issues_enabled: false
contact_links:
  - name: GayGram Desktop Issues
    url: https://github.com/DaiWicked/GayGramDesktop/issues
    about: Bug reports and feature requests for GayGram Desktop.
